### ISSUE TITLE
Enhancement Ideas

### ISSUE THREAD

**Issue by Sinfire** [golf1052/Twixel#5]
Thanks a lot for providing this API to the Twitch system.  There are a couple of things that would be helpful for future users:

1 - I noticed that the Total Streams value is missing when you call the RetrieveStreams function.  It would be nice to be able to see how many total streams there are on the system.

2 - Nice to have feature:  Have the language constants defined.  So that instead of EN, the user can display English.  

Thanks again for providing this great library.
-- Steve

**Comment by golf1052** [comment]
Just made #6. Should add the functionality you are asking about.

**Comment by Sinfire** [comment]
Tested both the Total on the Stream object and being able to display the full language,  and it is working great.

Thanks for the quick turnaround.

**Comment by golf1052** [comment]
Merged in changes, updated NuGet package, create new release. Thanks for the feedback.
