### ISSUE TITLE
JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

### ISSUE THREAD

**Issue by ibiza240** [golf1052/Twixel#9]
Hello,

let me say first that this API is great, I've been using it with success so far!

I encountered a surprising error while doing a simple query :

    var twixel = new TwixelAPI.Twixel("abc123xyz", "");
    var result = await twixel.RetrieveStreams(channels: listOfChannels);

got me a

    Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
       at Newtonsoft.Json.JsonTextReader.ParseValue()
       at Newtonsoft.Json.JsonTextReader.ReadInternal()
       at Newtonsoft.Json.JsonTextReader.Read()
       at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader)
       at Newtonsoft.Json.Linq.JObject.Parse(String json)
       at TwixelAPI.Twixel.<DoWebData>d__a5.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---

Unfortunately I don't know what was the content of `listOfChannels` at the time of the crash, but I am positive that it was a normal list of channels (streamers names)

Since I am not able to find the cause and fix it, I thought maybe you would make more sense of it than me.

**Comment by golf1052** [comment]
I created a branch and test for this issue: 5ff714896135e03176b243ed6cac121c5b764832

I'm not seeing it come up on my and but I think it's an issue I actually fixed recently (but haven't put up on NuGet yet). Basically sometimes Twitch sucks and doesn't send back a normal Twitch error response but instead sends an HTML error response. In [this commit](5adb1c66187bdd988ac1641694ffa290c8f0476c) I catch and throw an appropriate exception for the error.

**Comment by ibiza240** [comment]
Thanks for replying! I would gladly try the new version, but the commit link doesn't seem to be working

**Comment by golf1052** [comment]
Just pushed the latest source to NuGet: https://www.nuget.org/packages/Twixel/2.0.4

**Comment by golf1052** [comment]
Also fixed the commit link.

**Comment by ibiza240** [comment]
Thanks! Will try and let you know :)

**Comment by ibiza240** [comment]
It looks like you fixed it. Thanks!
